"""empty message

Revision ID: 0fc6260d4fe0
Revises: 20e56cee06e4
Create Date: 2018-07-24 11:59:28.674805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc6260d4fe0'
down_revision = '20e56cee06e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'person', ['email_address'])
    op.create_unique_constraint(None, 'students', ['student_id'])
    op.create_unique_constraint(None, 'subjects', ['subject_id'])
    op.create_unique_constraint(None, 'teachers', ['staff_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    # ### end Alembic commands ###
