"""empty message

Revision ID: 20e56cee06e4
Revises: 
Create Date: 2018-07-24 11:16:57.555251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e56cee06e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('person_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('email_address'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('teachers',
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_address'], ['person.email_address'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.staff_id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('students',
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_address'], ['person.email_address'], ),
    sa.ForeignKeyConstraint(['major_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('student_subject',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_subject')
    op.drop_table('students')
    op.drop_table('subjects')
    op.drop_table('teachers')
    op.drop_table('person')
    # ### end Alembic commands ###
