"""empty message

Revision ID: 594045b833e9
Revises: 0fc6260d4fe0
Create Date: 2018-07-24 15:16:13.820293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594045b833e9'
down_revision = '0fc6260d4fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('subjects', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subjects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('teachers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('teachers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'updated_at')
    op.drop_column('teachers', 'created_at')
    op.drop_column('subjects', 'updated_at')
    op.drop_column('subjects', 'created_at')
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'created_at')
    # ### end Alembic commands ###
